# askflow/.render.yaml
services:
  - type: web
    name: askflow-api  
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    env: python
    plan: free 
    port: 8000 
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"